name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        touch ~/.ssh/id_rsa
        touch ~/.ssh/id_rsa.pub
        pwd
    - name: Run SSH command
      run: |
        ssh-keyscan -H ${{ secrets.SSH_PROD_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PROD_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        rsync -avz --exclude='node_modules/' --exclude='.git/' /home/runner/work/osh-portal-state/osh-portal-state/ owoade@${{ secrets.SSH_PROD_HOST }}:~/osh-portal-state/
        ssh owoade@${{ secrets.SSH_PROD_HOST }} "cd osh-portal-state && docker stop osh-portal-state && docker rm osh-portal-state && docker rmi -f osh-portal-state && docker build -t osh-portal-state . && docker run -d --name=osh-portal-state -p 3000:3000 osh-portal-state"
